---
- hosts: servers
  become: yes
  tasks:
    - name: Actualizar cache de software de apt
      apt:
        update_cache: yes

    - name: Instalar apache
      apt:
        name: apache2
        state: present

    - name: Instalar cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear archivo
      copy:
        dest: /home/vagrant/archivo.txt
        content: "Este es un archivo creado por Ansible."

    - name: Copiar archivos
      copy:
        src: /ruta/local/al/archivo.txt
        dest: /home/vagrant/archivo_copiado.txt

    - name: Crear carpetas
      file:
        path: /home/vagrant/carpeta_creada
        state: directory

    - name: Iniciar un servicio
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Agregar un usuario al servidor
      user:
        name: nuevo_usuario
        state: present
        password: "{{ 'maseta2,0' | password_hash('sha512') }}"

    - name: Ejecutar un script en el servidor
      command: /home/vagrant/script.sh
